config/routes.rb
Rails.application.routes.draw do
  resources :histories
  resources :comments
  resources :projects
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: "projects#index"

  resources :projects do
    resources :comments, only: [:create, :destroy,]
  end
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :project
  belongs_to :user

  validates :previous_status, :new_status, presence: true
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :set_history, only: %i[ show edit update destroy ]

  # GET /histories or /histories.json
  def index
    @histories = History.all
  end

  # GET /histories/1 or /histories/1.json
  def show
  end

  # GET /histories/new
  def new
    @history = History.new
  end

  # GET /histories/1/edit
  def edit
  end

  # POST /histories or /histories.json
  def create
    @history = History.new(history_params)

    respond_to do |format|
      if @history.save
        format.html { redirect_to @history, notice: "History was successfully created." }
        format.json { render :show, status: :created, location: @history }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /histories/1 or /histories/1.json
  def update
    respond_to do |format|
      if @history.update(history_params)
        format.html { redirect_to @history, notice: "History was successfully updated." }
        format.json { render :show, status: :ok, location: @history }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /histories/1 or /histories/1.json
  def destroy
    @history.destroy!

    respond_to do |format|
      format.html { redirect_to histories_path, status: :see_other, notice: "History was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_history
      @history = History.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def history_params
      params.require(:history).permit(:project_id, :user_id, :previous_status, :new_status)
    end
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/views/histories/_form.html.erb
<%= form_with(model: history) do |form| %>
  <% if history.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(history.errors.count, "error") %> prohibited this history from being saved:</h2>

      <ul>
        <% history.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :project_id, style: "display: block" %>
    <%= form.text_field :project_id %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :previous_status, style: "display: block" %>
    <%= form.text_field :previous_status %>
  </div>

  <div>
    <%= form.label :new_status, style: "display: block" %>
    <%= form.text_field :new_status %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/histories/_history.html.erb
<div id="<%= dom_id history %>">
  <p>
    <strong>Project:</strong>
    <%= history.project_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= history.user_id %>
  </p>

  <p>
    <strong>Previous status:</strong>
    <%= history.previous_status %>
  </p>

  <p>
    <strong>New status:</strong>
    <%= history.new_status %>
  </p>

</div>

app/views/histories/edit.html.erb
<h1>Editing history</h1>

<%= render "form", history: @history %>

<br>

<div>
  <%= link_to "Show this history", @history %> |
  <%= link_to "Back to histories", histories_path %>
</div>

app/views/histories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Histories</h1>

<div id="histories">
  <% @histories.each do |history| %>
    <%= render history %>
    <p>
      <%= link_to "Show this history", history %>
    </p>
  <% end %>
</div>

<%= link_to "New history", new_history_path %>

app/views/histories/new.html.erb
<h1>New history</h1>

<%= render "form", history: @history %>

<br>

<div>
  <%= link_to "Back to histories", histories_path %>
</div>

app/views/histories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @history %>

<div>
  <%= link_to "Edit this history", edit_history_path(@history) %> |
  <%= link_to "Back to histories", histories_path %>

  <%= button_to "Destroy this history", @history, method: :delete %>
</div>