config/routes.rb
Rails.application.routes.draw do
  resources :histories
  resources :comments
  resources :projects
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: "projects#index"

  resources :projects do
    resources :comments, only: [:create, :destroy,]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectHistory</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container-flouid">
      <nav class="navbar navbar-expand-lg bg-light">
        <div class="container">
          <% if user_signed_in? %> 
            <div> Welcome <%= link_to current_user.email, edit_user_registration_path %> </div>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <%= link_to 'Projects', projects_path, class: 'nav-link active' %>
                </li>
              </ul>
            </div> 
            <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: 'btn btn-outline-success' %> 
          <% end %>
        </div>
      </nav>
      <div class="container">
        <% if notice.present? || alert.present? %>
          <p class="notice"><%= notice %></p> 
          <p class="alert"><%= alert %></p>
        <% end %>   
        <%= yield %>
      </div>
    </div> 
  </body>
</html>